### ISSUE TITLE
Shard ID is always null in production

### ISSUE THREAD

**Issue by johnboy14** [nervous-systems/hildebrand#9]
I have literally pulled the following code out of your blog post on consuming streams.  When I run this code against a local instance of dynamoDB I can retrieve the last shard-id using this code but when I try against an actual dynamodb table with a stream, there never seems to be a shard ID available.  It always comes back as null.  I am not really sure whats causing the problem here.

```
(defn read! [creds out-chan table-name]
  (go
    (let [stream-id (<! (latest-stream-arn! creds table-name))
          shard-id  (-> (describe-stream! creds stream-id)
                        <!! :shards last :shard-id)]
      (log/info (str "Consuming for Stream " stream-id " and shard " shard-id))
      (get-records! creds stream-id shard-id :latest {} {:chan out-chan}))))
```

I've tried debugging the describe-stream! function and I get the following exception.

```
(log/info  (-> (describe-stream! creds stream-id)
                        <!!))
```

```
INFO  com.pav.notification.comments.component: #error {
 :cause unknown-operation-exception: 
 :data {:type :unknown-operation-exception, :message nil}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message unknown-operation-exception: 
   :data {:type :unknown-operation-exception, :message nil}
   :at [clojure.core$ex_info invoke core.clj 4593]}]
 :trace
 [[clojure.core$ex_info invoke core.clj 4593]
  [eulalie.support$error__GT_throwable invoke support.cljc 17]
  [eulalie.support$issue_request_BANG_$fn__13408$state_machine__5777__auto____13409$fn__13411 invoke support.cljc 29]
  [eulalie.support$issue_request_BANG_$fn__13408$state_machine__5777__auto____13409 invoke support.cljc 22]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke ioc_macros.clj 940]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke ioc_macros.clj 944]
  [clojure.core.async.impl.ioc_macros$take_BANG_$fn__5793 invoke ioc_macros.clj 953]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__1448 invoke channels.clj 102]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}

```

**Comment by moea** [comment]
Thanks.  Which version of Hildebrand are you using?  The API has changed a little since that blog post - https://github.com/nervous-systems/hildebrand/wiki/hildebrand.streams - `hildebrand.streams/get-records!` now wants a shard iterator, and the `hildebrand.streams.page` namespace (containing the version of `get-records!` which obtains an iterator) is now `hildebrand.streams.channeled`.   But it sounds like your problem is in `describe-stream`?  Can you confirm that `latest-stream-arn` gives you a non empty string, and that you get `unknown-operation-exception` whenever you pass it to `describe-stream`?  

Note that `unknown-operation-exception` is an error type returned from the remote Dynamo service, which means that something unusual is happening.  What keys do you have in `creds` (are you passing a non-default `:region`, etc.)?

**Comment by moea** [comment]
N.B. the simplest way to accomplish the same with 0.4.1 is `(hildebrand.streams.channeled/get-records! creds stream-arn shard-id :latest)`, however errors will be harder to debug with that channel-only API, so it probably makes sense to move to it after something like `streams/get-records!` is working.

**Comment by moea** [comment]
Namespace qualified version, for clarity, which I'd expect to work:

``` clojure
(defn read! [creds out-chan table-name]
  (go
    (let [stream-id (<! (streams/latest-stream-arn! creds table-name))
          shard-id  (-> (streams/describe-stream! creds stream-id)
                        <! :shards last :shard-id)]
      (log/info (str "Consuming for Stream " stream-id " and shard " shard-id))
      (streams.channeled/get-records! creds stream-id shard-id :latest {} {:chan out-chan}))))
```

**Comment by johnboy14** [comment]
_latest-stream-arn_ returns a non empty string.  My creds are made up of my aws creds and an endpoint.  I am not specifying a region because the endpoint dictates that surely?.  I was wondering if my IAM profile requires additional access privileges to read streams?.  

```
:access-key "<<ACCESS_KEY>>"
 :secret-key "<<SECRET_KEY>>"
:endpoint "http://dynamodb.us-west-2.amazonaws.com"
```

I am using version 0.4.1.  I get the same problem with 0.4.0

**Comment by johnboy14** [comment]
I solved the problem.  It seems I had to include the _:region_ and drop the endpoint from the credientials.
The following works

```
:access-key "<<ACCESS_KEY>>"
 :secret-key "<<SECRET_KEY>>"
:region "us-west-2"
```

**Comment by moea** [comment]
Cool - you can specify either region or endpoint, however the streams endpoints are distinct from the Dynamo ones, which is why you were seeing the issue.  Don't hesitate to let me know if you run into other problems.
